name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
url: https://www.spoyfoundry.com
enforce_ssl: www.spoyfoundry.com
